name: .NET Core

env:
  IMAGE_NAME: githubactionstestapp
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Create and save Docker image
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: ${{ env.IMAGE_NAME }}.tar
      run: |
        docker build . \
          --tag $IMAGE_NAME:$GITHUB_SHA \
          --file GithubActionsTestApp/Dockerfile
        docker save \
          -o ${{ env.IMAGE_NAME }}.tar $IMAGE_NAME:$GITHUB_SHA   
      